### ISSUE TITLE
Run syscounters or block  occur error   

### ISSUE THREAD

**Issue by apcwowo** [facebookincubator/profilo#15]
python3 -m profilo.workflow_demo override-main-27575-2018-3-22T13-18-55-BgeHcWsbAsO-cs-f5457d96.log syscounters outpu
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Downloads/profilo-master/python/profilo/workflow_demo.py", line 255, in <module>
    args.func(tracefile, args)
  File "/Users//Downloads/profilo-master/python/profilo/workflow_demo.py", line 124, in syscounters
    trace = interpreter.interpret()
  File "/Users/Downloads/profilo-master/python/profilo/importer/interpreter.py", line 148, in interpret
    block_entries.end,
  File "/Users/Downloads/profilo-master/python/profilo/importer/interpreter.py", line 241, in assign_name
    assert len(self.children[key]) == 1
KeyError: BytesEntry(id=35950, type='STRING_KEY', arg1=35948, data='__name')

**Comment by BurntBrunch** [comment]
Hmm, interesting. I assume the trace is from the sample app? Do you mind uploading it here?

**Comment by BurntBrunch** [comment]
1) I'm glad you're using it in a real app :) 
2) The ` assert len(self.children[key]) == 1` check that it hits should be relaxed I suppose.

What's happening is that there are STRING_KEY and STRING_VALUE entries in the trace that attach key-value pairs of annotations. The VALUE entry should be a child of the KEY entry. In your case, it is 99% a `__name` = `some systrace name` pair. 

Somehow a KEY got logged without a corresponding VALUE. In hindsight, this is possible to happen if the trace stops at an inopportune time, so we shouldn't be asserting but silently skipping over the bad pair.

Feel free to submit a PR or we will get to it soon. :)

**Comment by ricardorey10** [comment]
Commit 1149bc0 addresses this issue..
