### ISSUE TITLE
Analyze the demo app log failed

### ISSUE THREAD

**Issue by dreamtalee** [facebookincubator/profilo#23]
I get the log follow the process in this page https://facebookincubator.github.io/profilo/docs/trace-processing.html, but cause exception when analyze it:

```
$ python3 -m profilo.workflow_demo b.log stacks b.apk 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dreamtale/develop/nice/profilo/python/profilo/workflow_demo.py", line 255, in <module>
    args.func(tracefile, args)
  File "/Users/dreamtale/develop/nice/profilo/python/profilo/workflow_demo.py", line 176, in stacks
    trace = interpreter.interpret()
  File "/Users/dreamtale/develop/nice/profilo/python/profilo/importer/interpreter.py", line 148, in interpret
    block_entries.end,
  File "/Users/dreamtale/develop/nice/profilo/python/profilo/importer/interpreter.py", line 248, in assign_name
    assert len(self.children[key]) == 1
AssertionError
```
the log file( the apk file can't upload correctly):

[b.log](https://github.com/facebookincubator/profilo/files/2068549/b.log)

**Comment by ricardorey10** [comment]
This seems to be a bug in the way we parse certain entry types. I'll have a fix for this soon. Thanks for raising this issue!

**Comment by ricardorey10** [comment]
As a side note, I see you're trying to process stacks with this trace. It turns out that getting stack traces is not yet supported in 8.x and you're using 8.1.0, so this particular demo won't work for you. We're currently in the process of redoing stack unwinding, so this type of support is much easier to forward-port.

**Comment by ricardorey10** [comment]
02f4abf fixes the assert problem. You should be able to run `blocks` and `syscounters` now. However, as mentioned above, `stacks` will not work for 8.x. We hope to have that functionality up and running soon =)
