### ISSUE TITLE
Sample App Crash

### ISSUE THREAD

**Issue by s1rius** [facebookincubator/profilo#43]
install release-96e2c3f and click START TRACING, App crash.
both real device and emulator.

```
Process: com.facebook.profilo.sample, PID: 20073
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:703)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:564)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:500)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
        at com.facebook.profilo.writer.NativeTraceWriter.initHybrid(Native Method)
        at com.facebook.profilo.writer.NativeTraceWriter.<init>(NativeTraceWriter.java:36)
        at com.facebook.profilo.logger.Logger.startWorkerThreadIfNecessary(Logger.java:181)
        at com.facebook.profilo.logger.Logger.postCreateTrace(Logger.java:110)
        at com.facebook.profilo.core.TraceControl.startTraceInternal(TraceControl.java:344)
        at com.facebook.profilo.core.TraceControl.startTrace(TraceControl.java:300)
        at com.facebook.profilo.controllers.external.api.ExternalTraceControl.startTrace(ExternalTraceControl.java:41)
        at com.facebook.profilo.sample.BaseSampleAppMainActivity$1.onClick(BaseSampleAppMainActivity.java:60)
        at android.view.View.performClick(View.java:6303)
        at android.widget.CompoundButton.performClick(CompoundButton.java:134)
        at android.view.View$PerformClick.run(View.java:24828)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by BurntBrunch** [comment]
This should be resolved now, sorry for the churn.
Please reopen this issue if the crash persists.
