### ISSUE TITLE
Sample App Crashes

### ISSUE THREAD

**Issue by Leland-Takamine** [facebookincubator/profilo#7]
Installed and ran the [sample apk](https://github.com/facebookincubator/profilo/releases/download/release-fef2654/sample.apk) for `release-fef2654`. Clicking the "Start tracing" button causes the following crash on an 8.1.0 device (Pixel 2):

```
03-14 12:04:14.259 19558 19558 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:442)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:367)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:332)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.profilo.writer.NativeTraceWriter.initHybrid(Native Method)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.profilo.writer.NativeTraceWriter.<init>(NativeTraceWriter.java:37)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.profilo.logger.Logger.startWorkerThreadIfNecessary(Logger.java:377)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.profilo.logger.Logger.postCreateTrace(Logger.java:271)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.profilo.core.TraceControl.startTraceInternal(TraceControl.java:327)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.profilo.core.TraceControl.startTrace(TraceControl.java:285)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.profilo.controllers.external.api.ExternalTraceControl.startTrace(ExternalTraceControl.java:42)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.facebook.profilo.sample.SampleAppMainActivity$1.onClick(SampleAppMainActivity.java:63)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at android.view.View.performClick(View.java:6294)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at android.widget.CompoundButton.performClick(CompoundButton.java:134)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24770)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-14 12:04:14.259 19558 19558 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by BurntBrunch** [comment]
Sorry about that, fix incoming.

**Comment by BurntBrunch** [comment]
https://github.com/facebookincubator/profilo/commit/d27746603fc71b8e21149f9ca0f92f0fe442440e fixes this.
